# Generated by Django 4.2.4 on 2023-08-28 20:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_alter_customuser_options_alter_customuser_managers_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="s_staff",
            new_name="is_staff",
        ),
    ]
