# Generated by Django 4.2.4 on 2023-08-28 11:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CADDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("2D", "2D Drawing"),
                            ("PDF", "PDF Drawing"),
                            ("3D", "3D Model File"),
                            ("Spec", "Specification"),
                        ],
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(upload_to="cad_documents/")),
                ("description", models.TextField(max_length=300)),
                (
                    "status",
                    models.CharField(
                        choices=[("actual", "Actual"), ("canceled", "Canceled")],
                        default="actual",
                        max_length=20,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("manager", "Manager"), ("engineer", "Engineer")],
                        max_length=20,
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone_number", models.CharField(max_length=20)),
                (
                    "access_status",
                    models.CharField(
                        choices=[
                            ("edit", "Full Edit Access"),
                            ("view", "View-Only Access"),
                        ],
                        default="view",
                        max_length=20,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("project_number", models.CharField(max_length=25)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "documents",
                    models.ManyToManyField(
                        blank=True,
                        related_name="projects",
                        to="document_flow.caddocument",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "change_datetime",
                    models.DateTimeField(default=datetime.datetime.now),
                ),
                ("description", models.TextField()),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="document_flow.caddocument",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="document_flow.customuser",
                    ),
                ),
            ],
        ),
    ]
