# Generated by Django 4.2.4 on 2023-09-01 13:04

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CADDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_number",
                    models.CharField(default="document number needed", max_length=50),
                ),
                (
                    "document_name",
                    models.CharField(
                        blank=True, default="document name needed", max_length=100
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("2D", "2D Drawing"),
                            ("PDF", "PDF Drawing"),
                            ("3D", "3D Model File"),
                            ("Spec", "Specification"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="media/cad_documents/"
                    ),
                ),
                ("description", models.TextField(max_length=300)),
                (
                    "status",
                    models.CharField(
                        choices=[("actual", "Actual"), ("canceled", "Canceled")],
                        default="actual",
                        max_length=20,
                    ),
                ),
                ("uploaded", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("project_number", models.CharField(max_length=25)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "documents",
                    models.ManyToManyField(
                        blank=True,
                        related_name="projects",
                        to="document_flow.caddocument",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="ChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "change_datetime",
                    models.DateTimeField(default=datetime.datetime.now),
                ),
                ("description", models.TextField()),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="document_flow.caddocument",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
