# Generated by Django 4.2.4 on 2023-08-29 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("document_flow", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="caddocument",
            old_name="created",
            new_name="uploaded",
        ),
        migrations.AddField(
            model_name="caddocument",
            name="uploaded_by",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
