# Generated by Django 4.2.4 on 2023-08-29 09:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("document_flow", "0002_rename_created_caddocument_uploaded_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="caddocument",
            options={"ordering": ["-uploaded"]},
        ),
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["-created"]},
        ),
    ]
